import { ChapterData, WeaponType, AttachmentType } from './types';

export const PROLOGUE_TEXT = "Marcus Vael spent eleven years in the marines and came home with two things: a photograph of a forest he had never seen before, torn from a geography magazine in a field hospital waiting room, and a certainty that he was finished with war. Not finished in the way soldiers say it — exhausted, traumatized, needing rest. Finished in the way a man is finished with something when he understands, bone-deep, that continuing would cost him whatever he still had left worth keeping. He bought a camera six months after his discharge. By the time he was thirty-four, Marcus Vael was one of the most published wildlife photographers working in the Asia-Pacific region. He understood what he was documenting — not just beauty, but the last of things. The final appearances. He heard about the Korrath Islands from a marine biologist named Estelle Chow at a conservation conference in Singapore. A chain of islands in the South Pacific, largely undocumented. Dense primary rainforest. Marine ecosystems untouched. And beneath it all, deposits of varantite — a rare mineral that had recently made it extraordinarily valuable. He booked a chartered boat three weeks later. He told no one where he was going except his editor in Sydney, who told him to be careful and meant it. He was not careful enough.";

export const CHAPTERS: ChapterData[] = [
  // ─── ACT ONE — Shipwreck Shore & Prison Camp ───
  {
    id: 1,
    act: 1,
    title: "Thirty Minutes of Wonder",
    location: "Shipwreck Shore",
    enemyCount: 0,
    medikitCount: 1,
    content: "The Korrath Islands appeared out of morning fog like something remembered rather than discovered — dense green walls of jungle rising sheer from the water, the canopy so thick and continuous it looked solid from a distance. The smell reached the boat before the visual detail did: wet earth, vegetation, brine, the particular sweetness of tropical flowers. Marcus stood at the bow with a camera body in his hand and forgot, for a moment, why he was there. He was simply looking. Simply present. He had thirty minutes of this. Then the Ironclad patrol boat came from behind the northern headland, moving at speed, grey-hulled and low in the water. Marcus was handcuffed with a cable tie and put in the patrol boat's hold. He did not see what happened to Rotu.",
    objectivePosition: [0, 30],
    objectiveLabel: "Reach the shoreline",
  },
  {
    id: 2,
    act: 1,
    title: "Block A",
    location: "Ironclad Prison Camp",
    enemyCount: 10,
    medikitCount: 1,
    content: "The prison camp occupied a clearing cut from the jungle with industrial efficiency — corrugated metal huts in functional rows, electrified perimeter wire, two watchtowers manned at all times. Block A contained seventeen prisoners when Marcus arrived. Most were Korrath islanders whose land now fell within Ironclad's operational perimeter. And there was Lena. She was sitting against the far wall — cross-legged, back straight, watching the door. She had memorized the guard schedule, identified two weaknesses in the perimeter wire, and decided that the man she was waiting for had not yet arrived. She looked at Marcus for four seconds. Then she said: 'You were military.' It was not a question.",
  },
  {
    id: 3,
    act: 1,
    title: "The Escape",
    location: "Prison Camp",
    enemyCount: 0,
    medikitCount: 1,
    unlocks: WeaponType.PISTOL,
    content: "Private Hewitt stopped outside Marcus's cell at 2 AM — twenty-two years old, visibly exhausted, at the tail end of a twelve-hour shift. Marcus had the rebar piece from Lena. He had been watching the buckle in the door frame for two days. It took nine minutes of careful work on the bolt mechanism. He took Hewitt's keys and sidearm — a scratched pistol with a crack running through the grip's left panel and a full magazine. Lena watched him check the safety, the chamber, the magazine seating. 'Can you shoot?' she asked. 'Yes.' 'Can you shoot accurately while moving?' 'Usually.' 'Good enough,' she said, and led them into the corridor.",
    objectivePosition: [40, -50],
    objectiveLabel: "Escape through the perimeter wire",
  },
  {
    id: 4,
    act: 1,
    title: "The Infirmary",
    location: "Prison Camp",
    enemyCount: 0,
    medikitCount: 3,
    content: "The maintenance corridor between the mess hut and equipment shed was a ninety-centimetre gap the camp's designers had created by accident. Lena had discovered it on day three by watching a rat disappear into a shadow that should not have been wide enough. Before the perimeter wire, she turned toward the infirmary — a single room smelling of antiseptic and mildew. Two medikits sat on the shelf, military-grade, sealed in their original packaging. Lena took both without pausing. 'For later,' she said. 'How much later?' She looked at him with an expression that was almost patience. 'There will be a later. That is the point.'",
    objectivePosition: [-30, 35],
    objectiveLabel: "Reach the infirmary",
  },
  {
    id: 5,
    act: 1,
    title: "The Shore",
    location: "Shipwreck Shore",
    enemyCount: 3,
    medikitCount: 1,
    unlocks: WeaponType.PISTOL,
    content: "The beach emerged suddenly — the trees ending at a definite line, the sand pale in the pre-dawn darkness. Marcus saw the wreck immediately: Rotu's boat, half-submerged on the reef, the superstructure burned to the waterline. Lena stopped at the water's edge. 'There may be something in the wreck. In the captain's compartment.' Marcus swam out. The water was warm. Inside a waterproof case strapped to the underside of a shelf: a pistol, identical to the one on his hip, sealed well enough that the saltwater had not touched it. The beach patrol — two guards walking the shoreline and one at the observation post above — would swing past in twelve minutes.",
  },
  {
    id: 6,
    act: 1,
    title: "Tomu",
    location: "Jungle Trail North",
    enemyCount: 3,
    medikitCount: 2,
    content: "The jungle trail north was narrow, barely a trail at all. Lena moved along it with the confidence of someone following something they know rather than something they can see. She stopped before they reached the third marker because she had smelled something Marcus had not yet registered. Tomu was a resistance fighter from the village of Kova-Sael — a man she had known since childhood. He was twenty-eight years old. She crouched beside him. Said his name quietly in Korrath. Then she reached into his jacket and removed a sealed medikit he had been carrying and had not been given the chance to use. 'He would want it used,' she said. The patrol that killed Tomu still walked this route — two guards moving in a loop and a patrol leader at the trail fork.",
  },
  // ─── ACT TWO — The Hunt Begins ───
  {
    id: 7,
    act: 2,
    title: "The Briefing",
    location: "Resistance Safehouse",
    enemyCount: 0,
    medikitCount: 1,
    content: "Lena explained Voss methodically, without emotion. Director Harlan Voss was fifty-one years old. He had built Ironclad Solutions over fifteen years into a corporation with defence contracts on four continents. He controlled the archipelago through three sector lieutenants: Mako ran the rainforest interior — a former mercenary built for violence. Serrin controlled the volcanic highlands — a tactician who wins through patience. Pryce held Voss Port's outer approaches — a true believer, the most dangerous kind. To reach Voss, you went through all three. 'You'll take point on the outpost operations,' Lena said. 'You move the way the jungle needs you to move. I'll coordinate the cells.'",
    objectivePosition: [0, -20],
    objectiveLabel: "Approach the planning table",
  },
  {
    id: 8,
    act: 2,
    title: "Outpost Kava-1",
    location: "Rainforest Interior",
    enemyCount: 12,
    medikitCount: 2,
    unlocks: WeaponType.RIFLE,
    content: "The resistance had been watching Outpost Kava-1 for three weeks. Twelve guards in two rotations, a communications tower, and a padlocked armory. Marcus took the outpost alone in the early morning fog that dropped visibility to fifteen metres. He came in from the river, staying low in the reeds. Twenty-two minutes. Twelve guards. Patient, methodical work — not quick, not dramatic. The crate in the armory had Ironclad's corporate logo stenciled on the lid. Inside: rifles, pistols, ammunition. The Kar98k he lifted was a different weight from the pistol — heavier, balanced for sustained use. Lena arrived forty minutes later. 'Now we have real tools.'",
  },
  {
    id: 9,
    act: 2,
    title: "Kova-Sael",
    location: "Village Ruins",
    enemyCount: 7,
    medikitCount: 2,
    unlocks: WeaponType.SHOTGUN,
    content: "Kova-Sael had been a village of forty-three families, occupied continuously for over two hundred years. The harvest barn — the largest structure, used for ceremonies — had been among the first to burn. What remained was a landscape of ash and salvage. The processing road ran through what had been the village square. Ironclad left a cleanup crew — three guards on the perimeter, two near the barn, two armed road workers. In the ruins of the barn, beneath collapsed timbers, Lena found what survived: 'The Woodcutter.' Her grandfather's shotgun, stored in a heavy canvas bag. She checked the mechanism. It worked. She held it out to Marcus. 'Take it. It needs to be used. That is what he made it for.'",
  },
  {
    id: 10,
    act: 2,
    title: "The River Bend",
    location: "Sector B River",
    enemyCount: 16,
    medikitCount: 4,
    content: "A resistance cell had brought down an Ironclad supply helicopter at the river bend using a launcher built from salvaged drone parts. The helicopter came down in the river — cargo netting caught in the exposed infrastructure, holding the relevant section above the waterline. Two guards patrolled the bank on a forty-minute rotation. The wider Sector B territory was more populated — a river crossing checkpoint with three guards, three patrol teams of two each, and a small outpost with five guards. Marcus waded upstream through chest-deep water against a current with genuine intention. Three medikits were in the starboard cargo net, still sealed.",
  },
  {
    id: 11,
    act: 2,
    title: "The Cliff",
    location: "Sector C Western Cliff",
    enemyCount: 4,
    medikitCount: 1,
    unlocks: WeaponType.RIFLE,
    content: "The ridge above Sector C had been used as a sniper position by an Ironclad soldier for two weeks before Marcus reached it. The sniper's resupply had failed three times — logistics fraying under resistance pressure — and the private had walked back to the main outpost, leaving his rifle because carrying it down the cliff face was difficult. Marcus found the nest exactly as it had been left — the rifle propped against the rock wall, scope mounted, full magazine, eleven loose rounds arranged in a line. Through the scope he saw Voss Port for the first time — buildings, docks, a processing facility — small and precise in the scope's circle, achievable and reachable. The cliff approach was guarded by two trail guards and two patrol guards below.",
  },
  {
    id: 12,
    act: 2,
    title: "Mako",
    location: "Sector C Enforcer Base",
    enemyCount: 25,
    medikitCount: 3,
    isBoss: true,
    bossName: "Lieutenant Mako",
    bossHP: 300,
    bossPhases: 2,
    content: "Lieutenant Mako had been in the violence business since nineteen. Large, quiet in the unsettling way that dangerous men sometimes are. His philosophy was simple: overwhelming force, applied without hesitation. The base reflected it — reinforced walls, overlapping guard fields, three watchtowers, continuous spotlights. Four guards on the outer fence, three in the towers, two at the gate, four in the inner yard, two at the generator, six in the barracks on alert, three elite bodyguards in body armour. And Mako himself — heavily armoured, a two-phase fight in a room not large enough for the number of people in it. He went down fighting, which was consistent with who he was.",
  },
  {
    id: 13,
    act: 2,
    title: "Serrin",
    location: "Serrin's Tactical Camp",
    enemyCount: 15,
    medikitCount: 2,
    isBoss: true,
    bossName: "Lieutenant Serrin",
    bossHP: 250,
    bossPhases: 1,
    content: "Serrin was a tactician — quiet, methodical, the kind of soldier who wins through patience rather than force. His base reflected that: fewer guards but positioned with overlapping sightlines that made stealth harder than Mako's brute-force perimeter. Three hidden tripwire alarm posts, two elevated platform snipers, five guards on the main camp floor, two in the comms room. Serrin himself waited in the command tent with two elite guards. He fell to patience — his own strength turned against him, because a tactician can be outwaited by someone willing to learn his patterns and exploit the one moment he had repeated too many times.",
  },
  {
    id: 14,
    act: 2,
    title: "Pryce",
    location: "Pryce's Jungle Outpost",
    enemyCount: 13,
    medikitCount: 2,
    isBoss: true,
    bossName: "Lieutenant Pryce",
    bossHP: 250,
    bossPhases: 1,
    content: "Pryce was a true believer, which was the most dangerous kind — the kind that didn't calculate risk because they had replaced calculation with conviction. His soldiers fought harder and didn't retreat. Three on the outer patrol, two at the gate, four in the inner compound. In the inner sanctum: three elite fanatics and Pryce himself. He fell to decisiveness — his fanaticism made him predictable at the critical moment, because people who have stopped calculating risk always leave the same gap in the same place. With all three sectors broken, Voss pulled inward. He consolidated every remaining soldier into Voss Port.",
  },
  // ─── ACT THREE — The Core ───
  {
    id: 15,
    act: 3,
    title: "Voss Port",
    location: "Voss Port Dockyard",
    enemyCount: 14,
    medikitCount: 2,
    unlocks: WeaponType.ASSAULT_RIFLE,
    content: "Voss Port had been built in fourteen months — a functioning fortified city from nothing but jungle. The dockyard was Marcus's entry point, the least watched approach. Three elite guards with M416s at the dock gate, four on the dockyard floor, one sniper on the crane platform, four inside the warehouse. Near the dockyard entrance, an armoured vehicle sat at a bad angle in a drainage ditch — burned, ammunition cooked off. A soldier thrown clear had been carrying an M416. Marcus picked it up. The rate of fire hit him physically — mechanical rapidity that transformed shooting into something almost industrial. This was what Ironclad's best soldiers carried. He now had one.",
  },
  {
    id: 16,
    act: 3,
    title: "The City",
    location: "Voss Port Streets",
    enemyCount: 30,
    medikitCount: 3,
    content: "Voss Port was a gauntlet. Every chokepoint converted into a defended position. Three barriers across the main street, each with two guards. Four snipers on rooftops with overlapping sightlines. Four street patrol squads of three men each, running timed loops that were clearly Serrin's design — even dead, the tactician's hand was visible. If the alarm triggered, eight garrison troops would pour from the barracks. Marcus moved the way the past weeks had taught him — not with speed, but with patience. Identifying sightlines. Finding shadows. Working systematically from the edges inward.",
  },
  {
    id: 17,
    act: 3,
    title: "The Medical Facility",
    location: "Voss Port Medical",
    enemyCount: 5,
    medikitCount: 5,
    content: "The medical facility was toward the city's centre, behind a wall bearing Ironclad's corporate logo in metal lettering. Lightly guarded — two at the entrance, two making rounds inside, one in the supply corridor. Not a combat priority. Inside, past the wards sorted by rank, was the supply room. Steel cabinet, code-locked. The keypad's wear pattern suggested a four-digit code used frequently. In the adjacent room — the medical administrator's office — a notepad lay open to a page bearing a four-digit number circled twice. Four medikits in the cabinet. Sealed, military-grade, the best available. The largest health cache in the entire campaign.",
  },
  {
    id: 18,
    act: 3,
    title: "Voss Port HQ",
    location: "Voss Port Headquarters",
    enemyCount: 21,
    medikitCount: 3,
    content: "Voss Port Headquarters stood above the docks overlooking the sea — a structure both functional and theatrical. Pryce's surviving fanatics had been folded into the HQ defence. Four elite guards on the outer perimeter, three at the entrance, five guards on each of two interior floors. And at the top floor corridor before reaching Voss's remaining forces: four elite bodyguards with maximum armour and M416s. The building was a vertical gauntlet — each floor harder than the last, each corridor tighter, each angle more dangerous.",
  },
  {
    id: 19,
    act: 3,
    title: "Checkpoint Kova",
    location: "Volcanic Road",
    enemyCount: 12,
    medikitCount: 2,
    isMinisBoss: true,
    miniBossName: "Captain Carver",
    miniBossHP: 200,
    content: "The road from Voss Port to the volcano ran eighteen kilometres through rising terrain. Checkpoint Kova controlled the only paved approach — positioned where the road narrowed between two rock faces. Three guards at the main gate, four on barrier patrol, two in the watchtower, two at the sensor monitoring post. And Captain Carver in the generator room — a methodical, precise man who had not varied his patrol circuit by more than ninety seconds in three months. The shift change window was six minutes. Marcus took it. Carver went down at 0347 precisely. His M416 was fully loaded — 120 rounds, maintained with meticulous care.",
  },
  {
    id: 20,
    act: 3,
    title: "The Last Conversation",
    location: "Lava Tube",
    enemyCount: 0,
    medikitCount: 4,
    content: "The lava tube had been known to the Korrath people for generations — invisible from any aerial survey, accessible only through a scramble down a basalt slope that required knowing where to step. Lena was waiting at the entrance. Behind her: four resistance fighters and everything the resistance had left. One M416 with a full 120-round load, one shotgun with 24 shells, three medikits. She laid it on the flat section of rock with careful precision. 'The detonation chamber is at the lowest level,' she said. 'The chain reaction would take four to six minutes. The entire archipelago.' 'Come back first,' she said. 'Then we'll argue about the shotgun.'",
    objectivePosition: [0, -40],
    objectiveLabel: "Enter the lava tube",
  },
  {
    id: 21,
    act: 3,
    title: "Volcanic Mountain Road",
    location: "Volcanic Mountain",
    enemyCount: 14,
    medikitCount: 2,
    content: "The road between the checkpoint and the facility entrance — open terrain, exposed, the most dangerous stretch of the game. The highland air was different from the jungle below — thinner, carrying the mineral edge of volcanic activity. Two patrol convoys of three guards each moved along the road. Three roadside guard posts held two guards each. Two drone operators on the ridge controlled patrol drones — eliminating them would disable aerial surveillance. The mountain was visible against the sky, darker than the darkness around it, its silhouette shaped by centuries of geological activity. Somewhere inside was the thing Voss had built.",
  },
  {
    id: 22,
    act: 3,
    title: "The Core — Level 1",
    location: "Processing Tunnels",
    enemyCount: 11,
    medikitCount: 2,
    content: "The Varantite Core facility was entered through a maintenance access point requiring a coded override — the code decrypted from Carver's field tablet. Beyond: a descending tunnel of hewn rock and installed infrastructure, the walls bare volcanic basalt on the outer surface and Ironclad corporate installation on the inner. Processing tunnels three metres wide, varying ceiling heights, pools of condensation on the floor. Three guards at the entrance, six across three zones in the processing floor patrol, two armed operators in the control room. Marcus moved through them carefully — corridor-by-corridor, one zone at a time, moving inward.",
  },
  {
    id: 23,
    act: 3,
    title: "The Core — Level 2",
    location: "Detonation Chamber",
    enemyCount: 9,
    medikitCount: 2,
    content: "The detonation chamber entrance was guarded by four elite soldiers — Voss's personal security detail, transferred when Voss understood the outer perimeter was lost. They were better than anything Marcus had faced in Voss Port. Three more guards in the chamber interior. Two at the emergency stairwell. The chamber itself was a natural geological cavity fifty metres across and thirty metres high, varantite deposits glowing faintly in the walls. At its centre: the device — a configuration of varantite charges around a central activation mechanism. Marcus disabled the detonation sequence from the control panel. Eleven minutes. Multiple authorisation steps. The network went dark.",
  },
  {
    id: 24,
    act: 3,
    title: "The Trophy",
    location: "Voss's Office",
    enemyCount: 5,
    medikitCount: 2,
    isBoss: true,
    bossName: "Director Harlan Voss",
    bossHP: 400,
    bossPhases: 3,
    content: "Harlan Voss's office was at the top of the facility because he liked to look at the things he owned. Floor-to-ceiling glass, a mahogany desk carried down at considerable logistical effort, and on the north wall: a custom-engraved shotgun with 'V.O.S.S.' worked into the metal. Marcus took it. Voss came in with four elite bodyguards and the composure of a man who has decided that composure is the final thing he can control. 'You disabled it,' Voss said. 'Do you understand what varantite actually represents?' 'I understand that you killed people for it,' Marcus said. 'That's the relevant part.' Then Voss reached for his sidearm.",
  },
  {
    id: 25,
    act: 3,
    title: "After",
    location: "Korrath Islands",
    enemyCount: 0,
    medikitCount: 1,
    content: "The facility's emergency access tunnel came out on the eastern slope of the volcano in the early hours of morning. Lena was at the lava tube entrance with seven resistance fighters. 'The detonation system?' 'Disabled.' 'Voss?' 'Gone.' The Ironclad garrison, leaderless and cut off, began its own disintegration. The Korrath people returned to their sectors. Lena walked through the ruins of Kova-Sael on the first morning back. Marcus stayed for two months — photographing the rebuilding, the reef, the jungle. When he finally left, he left the pistols at the safehouse and the Woodcutter in Kova-Sael. The islands were real. They were still here. That was not nothing.",
    objectivePosition: [0, 50],
    objectiveLabel: "Walk to the eastern shore",
  }
];

export const ATTACHMENTS_DATA = {
  [AttachmentType.SCOPE]: {
    name: 'ACOG Scope',
    description: 'Enhances aiming zoom for precision shots.'
  },
  [AttachmentType.SILENCER]: {
    name: 'Suppressor',
    description: 'Reduces muzzle flash and noise.'
  },
  [AttachmentType.EXTENDED_MAG]: {
    name: 'Extended Mag',
    description: 'Increases magazine capacity by 50%.'
  },
  [AttachmentType.RECOIL_CONTROLLER]: {
    name: 'Recoil Controller',
    description: 'Reduces weapon recoil for better sustained fire accuracy.'
  }
};

export const WEAPONS_DATA = {
  [WeaponType.KNIFE]: {
    type: WeaponType.KNIFE,
    name: "Combat Knife",
    damage: 50,
    range: 3,
    ammo: 1,
    maxAmmo: 1,
    reserve: 0,
    fireRate: 0.5,
    reloadTime: 0,
    description: "A medium combat knife. Silent and deadly at close range. Marcus's first tool of survival — no bullets needed, just proximity and resolve.",
    attachments: []
  },
  [WeaponType.PISTOL]: {
    type: WeaponType.PISTOL,
    name: "Glock 19",
    damage: 25,
    range: 25,
    ammo: 15,
    maxAmmo: 15,
    reserve: 45,
    fireRate: 0.3,
    reloadTime: 1.5,
    description: "A reliable 9mm sidearm. Compact and effective at medium range. The first weapon Marcus takes from a guard — scratched, cracked in the grip, and imperfect. A desperate man's weapon.",
    attachments: []
  },
  [WeaponType.SHOTGUN]: {
    type: WeaponType.SHOTGUN,
    name: "The Woodcutter",
    damage: 100,
    range: 12,
    ammo: 8,
    maxAmmo: 8,
    reserve: 24,
    fireRate: 0.8,
    reloadTime: 2.5,
    description: "Found in the ruins of Kova-Sael beneath the collapsed harvest barn. Lena's grandfather carved the grip himself. Devastating at close range. More than a weapon — a memorial.",
    attachments: []
  },
  [WeaponType.RIFLE]: {
    type: WeaponType.RIFLE,
    name: "Kar98k",
    damage: 100,
    range: 100,
    ammo: 10,
    maxAmmo: 10,
    reserve: 40,
    fireRate: 0.5,
    reloadTime: 3.0,
    description: "A bolt-action precision rifle. Found in Outpost Kava-1's armory crate and later as a scoped variant on an abandoned cliff nest. Unmatched accuracy at long distances.",
    attachments: []
  },
  [WeaponType.ASSAULT_RIFLE]: {
    type: WeaponType.ASSAULT_RIFLE,
    name: "M416",
    damage: 34,
    range: 50,
    ammo: 30,
    maxAmmo: 30,
    reserve: 120,
    fireRate: 0.06,
    reloadTime: 2.0,
    description: "High-performance assault rifle carried by Ironclad's elite garrison troops. Found beside a dead soldier at a burnt armored vehicle in Voss Port Dockyard. Mechanical rapidity that transforms shooting into something almost industrial.",
    attachments: []
  },
  [WeaponType.REVOLVER]: {
    type: WeaponType.REVOLVER,
    name: "Police Revolver",
    damage: 50,
    range: 20,
    ammo: 6,
    maxAmmo: 6,
    reserve: 30,
    fireRate: 0.6,
    reloadTime: 3.5,
    description: "A heavy-hitting revolver. Slow but powerful. Each round hits like a verdict — limited ammunition demands precision over panic.",
    attachments: []
  }
};
